### PR TITLE
OSAC 71 - Migrate UiPath.Java.Activities to .NET Core

### PR DESCRIPTION
**Pull request by alcxs**
Description
Migrate Java Activities to multi-targeting (net461;net50-windows)
How to test
Build UiPath.Java.Packaging and import Nupkg in Uipath Studio to test.
Jira
[OSAC-71](https://uipath.atlassian.net/browse/OSAC-71)
Label:
24S

### CODE REVIEW

**Comment by sandupetrasco** [comment]
It looks like this PR (together with the others) could not pass the build, because of the GitHub user permissions..
Check this for reference:
same code , internal user (myself) -> https://github.com/UiPath/Community.Activities/pull/112
result -> [Java pipeline](https://uipath.visualstudio.com/Community/_build/results?buildId=1443485&view=logs&j=e1a3aa8c-2fec-5085-79fe-7474b8414b3b&t=e1a3aa8c-2fec-5085-79fe-7474b8414b3b)
Conclusion: we have to reconsider the external developers' permissions.

**Comment by alcxs** [comment]
will recreate from repo, not fork

**Pull request closed without merging**
